/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as appDashboardRouteImport } from './routes/(app)/dashboard'
import { Route as appRestaurantsIdRouteImport } from './routes/(app)/restaurants/$id'
import { Route as appSettingsTeamsIdRouteRouteImport } from './routes/(app)/settings/teams/$id/route'
import { Route as appSettingsTeamsIdIndexRouteImport } from './routes/(app)/settings/teams/$id/index'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const appDashboardRoute = appDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => appRouteRoute,
} as any)
const appRestaurantsIdRoute = appRestaurantsIdRouteImport.update({
  id: '/restaurants/$id',
  path: '/restaurants/$id',
  getParentRoute: () => appRouteRoute,
} as any)
const appSettingsTeamsIdRouteRoute = appSettingsTeamsIdRouteRouteImport.update({
  id: '/settings/teams/$id',
  path: '/settings/teams/$id',
  getParentRoute: () => appRouteRoute,
} as any)
const appSettingsTeamsIdIndexRoute = appSettingsTeamsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appSettingsTeamsIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof appDashboardRoute
  '/restaurants/$id': typeof appRestaurantsIdRoute
  '/settings/teams/$id': typeof appSettingsTeamsIdRouteRouteWithChildren
  '/settings/teams/$id/': typeof appSettingsTeamsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof appDashboardRoute
  '/restaurants/$id': typeof appRestaurantsIdRoute
  '/settings/teams/$id': typeof appSettingsTeamsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/dashboard': typeof appDashboardRoute
  '/(app)/restaurants/$id': typeof appRestaurantsIdRoute
  '/(app)/settings/teams/$id': typeof appSettingsTeamsIdRouteRouteWithChildren
  '/(app)/settings/teams/$id/': typeof appSettingsTeamsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/restaurants/$id'
    | '/settings/teams/$id'
    | '/settings/teams/$id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/restaurants/$id' | '/settings/teams/$id'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/(app)/dashboard'
    | '/(app)/restaurants/$id'
    | '/(app)/settings/teams/$id'
    | '/(app)/settings/teams/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/dashboard': {
      id: '/(app)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/restaurants/$id': {
      id: '/(app)/restaurants/$id'
      path: '/restaurants/$id'
      fullPath: '/restaurants/$id'
      preLoaderRoute: typeof appRestaurantsIdRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/teams/$id': {
      id: '/(app)/settings/teams/$id'
      path: '/settings/teams/$id'
      fullPath: '/settings/teams/$id'
      preLoaderRoute: typeof appSettingsTeamsIdRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/teams/$id/': {
      id: '/(app)/settings/teams/$id/'
      path: '/'
      fullPath: '/settings/teams/$id/'
      preLoaderRoute: typeof appSettingsTeamsIdIndexRouteImport
      parentRoute: typeof appSettingsTeamsIdRouteRoute
    }
  }
}

interface appSettingsTeamsIdRouteRouteChildren {
  appSettingsTeamsIdIndexRoute: typeof appSettingsTeamsIdIndexRoute
}

const appSettingsTeamsIdRouteRouteChildren: appSettingsTeamsIdRouteRouteChildren =
  {
    appSettingsTeamsIdIndexRoute: appSettingsTeamsIdIndexRoute,
  }

const appSettingsTeamsIdRouteRouteWithChildren =
  appSettingsTeamsIdRouteRoute._addFileChildren(
    appSettingsTeamsIdRouteRouteChildren,
  )

interface appRouteRouteChildren {
  appDashboardRoute: typeof appDashboardRoute
  appRestaurantsIdRoute: typeof appRestaurantsIdRoute
  appSettingsTeamsIdRouteRoute: typeof appSettingsTeamsIdRouteRouteWithChildren
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appDashboardRoute: appDashboardRoute,
  appRestaurantsIdRoute: appRestaurantsIdRoute,
  appSettingsTeamsIdRouteRoute: appSettingsTeamsIdRouteRouteWithChildren,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
